### PR TITLE
Code changes for django 2.0 compatibility

### PR DESCRIPTION
**Pull request by jon-torodash**
I've made some minor tweaks (branched off of master) to get this middleware compatible with Django 2.x. All tests pass. Any chance this could be merged in and a version bump published to pip? I'd be happy to make reasonable changes if requested.

Note that I removed all bytes fields. Tests ran into some problems which I traced all the way to django.db.models.query.ModelIterable within the query engine, which was de-serializing the `b'` prefix into the actual value. I noticed some apparent inconsistent use anyway in the IPRestrict source, in the declaration of `TYPE_LOCATION` and `TYPE_RANGE` in `django-iprestrict/iprestrict/models.py`. It seemed prudent to just use plain strings, as this data is not that large, and the [Django API docs](https://docs.djangoproject.com/en/2.0/ref/models/fields/#choices) always use string types in supporting examples.

### CODE REVIEW

**Comment by jon-torodash** [comment]
Not sure about this CI failure... the details are not even referencing the right commit. Will try to kick off another one.

**Comment by jon-torodash** [comment]
Okay, now I'm seeing the problem: Travis-CI is trying to run against pre Django 2.0. Will address this...

**Comment by jon-torodash** [comment]
In addition to the backward incompatibilities with the Django project, v2.0 dropped support for Python 2.x. Let me know if you'd like me to do anything else as a condition of merging in.

**Comment by sztamas** [comment]
Hi there,

First of all thanks for the contribution!

I glanced over the changes, what would prevent me to merge them in as they are for sure is the dropping of Django 1.8 - 1.10 from the tox config.
The oldest version was 1.8, which is LTS, and it is supported until at least April 2018 according to: https://www.djangoproject.com/download/

I think we should be doing our best to support 1.8, and not leaving possible projects that are still using it behind. Also if we do support 1.8, I don't see any reason not to also support all the versions released after it. That would mean also adding 1.11 to the tox file, which is currently missing but it is another LTS release.

The error you've got from Travis is caused by Django 2.0 package restructuring not python 2 - 3 differences and it should be solved by a conditional import to support both Django 2.x and pre-2.0 versions of Django.

Would it be possible for you to make those changes?

Thanks,

Tamas

**Comment by jon-torodash** [comment]
I'll have to think a bit about how to isolate conditional changes in the code in order to neatly supporting both versions simultaneously without simply writing bad Python. Since this is a semver bump on the major version number, the backwards incompatibilities are expected. Pip isn't too great about dependency isolation though, so I understand your concern. Will get back to you shortly with an improvement. I'll do what I can to restore the tox config, but just so we're clear, [Django 2.x explicitly lacks Python 2 support](https://docs.djangoproject.com/en/2.0/releases/2.0/)

**Comment by sztamas** [comment]
Just try/catch ImportError around the pre-2.0 import and import in the 2.+ way in the except.
It is common practice, for example

https://github.com/django/django/blob/3dcc3516914f25b58bde9312831f1d94b05cdb53/django/core/serializers/pyyaml.py#L20
 
Yes, I understand that Django 2.x lacks Python 2 support, but up to Django 2.0 python 2 was supported and we don't want to break projects that don't intend to upgrade to Django 2 yet. At least if all it takes to keep the backward compatibility isn't too much of an effort of course.

So, you could be on python 2 or python 3 with any of Django 1.8 - 1.11. 
You have to be on python 3 for Django 2.0.

Or those are valid so that's what we should have in the tox config.

**Comment by jon-torodash** [comment]
Made all of the changes requested, and the build is clean. If you're happy with it, I'll squash it for you so we can get this update out as soon as possible.

**Comment by sztamas** [comment]
@jon-torodash thanks again for the contribution!
I made some minor changes, but 1.5.0 is released and uploaded to PyPi.

**Comment by jon-torodash** [comment]
Thank you for finishing.

**Pull request merged**
