### PR TITLE
Fix for adding IP with invalid cidr_prefix_length (#5)

### PR DESCRIPTION
**Pull request by mradochonski**
Correct validation of CIDR in admin.py

### CODE REVIEW

**Comment by rvl** [comment]
Thanks for finding the problem. The clean of `cidr_prefix_length` can still be in its own method. I think the key is just to replace `cleaned_data['cidr_prefix_length']` with `cleaned_data.get('cidr_prefix_length', None)`.

**Comment by mradochonski** [comment]
No worries Rodney. I realized that myself but after pushing the change ;)

Thank you

Regards,
Maciej Radochonski

**Comment by rvl** [comment]
What you can do is `git commit -a --amend -m "Fix #5 Adding IP with CIDR fails" && git push origin +maciej` and that will rewrite the pull request.

**Comment by mradochonski** [comment]
Thanks Rodney, will do.

Thank you

Regards,
Maciej Radochonski

**Pull request closed without merging**
